# Source standard packages needed in performance scripting

library(zoo)
library(xts)
library(tidyverse)
library(lubridate)
library(reshape2)
library(scales)
library(PerformanceAnalytics)
library(knitr)
library(gridExtra)
library(kableExtra)
library(rmarkdown)
library(markdown)
library(bookdown)
library(xtable)
library(magrittr)
library(readxl)
library(tbl2xts)
library(stringr)
library(data.table)
library(bdscale)
library(ggthemes)
library(ggpubr)
library(ggrepel)
library(grid)
library(png)
library(asrsMethods)
library(asrsPalettes)

PME.palette <- c("#8B281F" ,"#D57030", "#00743F", "#5398D9", "#14325C","#512DA8")

options(scipen = 999)
options(xtable.comment = FALSE)
options(tinytex.verbose = TRUE)